USE [master]
GO
/****** Object:  Database [RatingDB]    Script Date: 14-05-2026 20:54:08 ******/
CREATE DATABASE [RatingDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RatingDB', FILENAME = N'C:\Users\lenovo\RatingDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RatingDB_log', FILENAME = N'C:\Users\lenovo\RatingDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [RatingDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RatingDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RatingDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RatingDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RatingDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RatingDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RatingDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [RatingDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [RatingDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RatingDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RatingDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RatingDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RatingDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RatingDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RatingDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RatingDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RatingDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [RatingDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RatingDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RatingDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RatingDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RatingDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RatingDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RatingDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RatingDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [RatingDB] SET  MULTI_USER 
GO
ALTER DATABASE [RatingDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RatingDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RatingDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RatingDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RatingDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RatingDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [RatingDB] SET QUERY_STORE = OFF
GO
USE [RatingDB]
GO
/****** Object:  Table [dbo].[Ratings]    Script Date: 14-05-2026 20:54:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ratings](
	[RatingId] [int] IDENTITY(1,1) NOT NULL,
	[StudentId] [int] NOT NULL,
	[TopicId] [int] NOT NULL,
	[Rating] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RatingId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RescheduledTopics]    Script Date: 14-05-2026 20:54:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RescheduledTopics](
	[RescheduleId] [int] IDENTITY(1,1) NOT NULL,
	[TopicName] [nvarchar](200) NULL,
	[SubjectId] [int] NULL,
	[TeacherId] [int] NULL,
	[RescheduleDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[RescheduleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Subjects]    Script Date: 14-05-2026 20:54:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Subjects](
	[SubjectId] [int] IDENTITY(1,1) NOT NULL,
	[SubjectName] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SubjectId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Topics]    Script Date: 14-05-2026 20:54:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Topics](
	[TopicId] [int] IDENTITY(1,1) NOT NULL,
	[SubjectId] [int] NOT NULL,
	[TopicName] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TopicId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 14-05-2026 20:54:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
	[Role] [varchar](20) NOT NULL,
	[CPI] [float] NULL,
	[Attendance] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RescheduledTopics] ADD  DEFAULT (getdate()) FOR [RescheduleDate]
GO
ALTER TABLE [dbo].[Ratings]  WITH CHECK ADD FOREIGN KEY([StudentId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Ratings]  WITH CHECK ADD FOREIGN KEY([TopicId])
REFERENCES [dbo].[Topics] ([TopicId])
GO
ALTER TABLE [dbo].[Topics]  WITH CHECK ADD FOREIGN KEY([SubjectId])
REFERENCES [dbo].[Subjects] ([SubjectId])
GO
ALTER TABLE [dbo].[Ratings]  WITH CHECK ADD CHECK  (([Rating]>=(1) AND [Rating]<=(5)))
GO
USE [master]
GO
ALTER DATABASE [RatingDB] SET  READ_WRITE 
GO
